import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import React, { useEffect } from 'react'
import Layout from '@/components/layouts/layout'
import { NextPageWithLayout } from './_app'
import Script from 'next/script'
import { useRecoilState } from 'recoil'
import { PayObjectState } from '@/state/PayObjectState'
import { IBM_Plex_Sans_KR } from 'next/font/google'
import { NextFont } from 'next/dist/compiled/@next/font'

const ibmPlexSansKR = IBM_Plex_Sans_KR({
  subsets: ['latin'],
  weight: '400',
});


const Home: NextPageWithLayout = () => {

  return (
    <>
    {/* JQuery */}
    <Script src="https://code.jquery.com/jquery-1.12.4.min.js" strategy="beforeInteractive"/>
    {/* iamport-payment */}
    <Script src="https://cdn.iamport.kr/js/iamport.payment-1.2.0.js" strategy="beforeInteractive" />
    <Link href="/products">
      <Head>
        <title>POS main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ibmPlexSansKR.className}>
        <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/images/main_logo.png"
              alt="main Logo"
              width={800}
              height={800}
            />
        </div>
          <div className={styles.font}>
            <h1>
              계산을 진행하시려면, 화면을 터치해주세요.
            </h1>
          </div>
      </main>
      </Link>
    </>
  );
}

Home.getLayout = function getLayout(page: React.ReactNode) {
  return(
    <>
    <Layout>
      {page}
    </Layout>
    </>
  )
}

export default Home
