import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import Layout from '@/components/layouts/layout'
import { NextPageWithLayout } from './_app'
import Script from 'next/script'
import { RecoilRoot, useRecoilState, useRecoilValue } from 'recoil'
import { PayObjectState } from '@/state/PayObjectState'
import { IBM_Plex_Sans_KR } from '@next/font/google'
import axios from 'axios';
import { LanguageIndexState } from '@/state/LanguageIndexState'
import { LanguageDataType } from '@/types/LanguageDataType'
import Header from '@/components/Header'
import { mapToBE } from '@/components/globalfunctions/mapToBE'

const ibmPlexSansKR = IBM_Plex_Sans_KR({
  subsets: ['latin'],
  weight: '400',
});

export default function Home() {
  const [languageIndex, setLanguageIndex] = useRecoilState(LanguageIndexState);  
  const [languageDatas, setLanguageDatas] = useState<LanguageDataType>({});
  
  const layoutName = 'L0000';
  const bodyName = 'B0000';
  useEffect(() => {
    const url = mapToBE(`/api/v1/translation/${languageIndex}/${bodyName}`);
    // const url = `http://localhost:8080/api/v1/translation/${languageIndex}/${bodyName}`;
    console.log("url: ", url);
    axios.get(url)
    .then((res) => setLanguageDatas(res.data))
    .catch((err) => console.log("err: ", err));
  }, [languageIndex])

  return (
    <>
    {/* JQuery */}
    <Script src="https://code.jquery.com/jquery-1.12.4.min.js" strategy="beforeInteractive"/>
    {/* iamport-payment */}
    <Script src="https://cdn.iamport.kr/js/iamport.payment-1.2.0.js" strategy="beforeInteractive" />
    <Header
      languageIndex={languageIndex}
      setLanguageIndex={setLanguageIndex}
      layoutName={layoutName}
    />
    <Link href="/products">
      <Head>
        <title>POS main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={ibmPlexSansKR.className}>
        <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/images/main_logo.png"
              alt="main Logo"
              width={800}
              height={800}
            />
        </div>
          <div className={styles.font}>
            <h1>
              {languageDatas.one}
            </h1>
          </div>
      </main>
      </Link>
    </>
  );
}

// Home.getLayout = function getLayout(page: React.ReactNode) {
//   return(
//     <>
//         {/* <Layout> */}
//           {page}
//         {/* </Layout> */}
//     </>
//   )
// }

// export default Home
