import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import React from 'react'
import Layout from '@/components/layouts/layout'
import { NextPageWithLayout } from './_app'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPageWithLayout = () => {
  return (
    <>
    <Link href="/products">
      <Head>
        <title>POS main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/images/main_logo.png"
              alt="main Logo"
              width={800}
              height={800}
            />
        </div>
          <div className={styles.font}>
            <h1>
              계산을 진행하시려면, 화면을 터치해주세요.
            </h1>
          </div>
      </main>
      </Link>
    </>
  );
}

Home.getLayout = function getLayout(page: React.ReactNode) {
  return(
    <>
    <Layout>
      {page}
    </Layout>
    </>
  )
}

export default Home
